"""Remove unique constraint on imdb_id

Revision ID: 7f66c9ee01ee
Revises: c7f346f338fb
Create Date: 2023-05-24 02:17:54.986907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f66c9ee01ee'
down_revision = 'c7f346f338fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actor_imdb_id_key', 'actor', type_='unique')
    op.drop_constraint('director_imdb_id_key', 'director', type_='unique')
    op.drop_constraint('genre_imdb_id_key', 'genre', type_='unique')
    op.drop_constraint('movie_imdb_id_key', 'movie', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('movie_imdb_id_key', 'movie', ['imdb_id'])
    op.create_unique_constraint('genre_imdb_id_key', 'genre', ['imdb_id'])
    op.create_unique_constraint('director_imdb_id_key', 'director', ['imdb_id'])
    op.create_unique_constraint('actor_imdb_id_key', 'actor', ['imdb_id'])
    # ### end Alembic commands ###
